#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleSandbox
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="WacTest")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbmp_ag(bmp_ag instance);
    partial void Updatebmp_ag(bmp_ag instance);
    partial void Deletebmp_ag(bmp_ag instance);
    partial void Insertlist_BMPCode(list_BMPCode instance);
    partial void Updatelist_BMPCode(list_BMPCode instance);
    partial void Deletelist_BMPCode(list_BMPCode instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleSandbox.Properties.Settings.Default.wacConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<bmp_ag> bmp_ags
		{
			get
			{
				return this.GetTable<bmp_ag>();
			}
		}
		
		public System.Data.Linq.Table<list_BMPCode> list_BMPCodes
		{
			get
			{
				return this.GetTable<list_BMPCode>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="Ag.FarmNMCPAwardHistory")]
		public ISingleResult<FarmNMCPAwardHistoryResult> FarmNMCPAwardHistory([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> fk_farmBusiness, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="SmallInt")] System.Nullable<short> lastCreditYear)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), fk_farmBusiness, lastCreditYear);
			return ((ISingleResult<FarmNMCPAwardHistoryResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.bmp_ag")]
	public partial class bmp_ag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pk_bmp_ag;
		
		private int _fk_farmBusiness;
		
		private string _fk_pollutant_category_code;
		
		private string _bmp_nbr;
		
		private string _description;
		
		private System.Nullable<byte> _lifespan_year;
		
		private System.Nullable<decimal> _fk_bmpPractice_code;
		
		private string _location;
		
		private System.Nullable<decimal> _units_planned;
		
		private string _fk_unit_code;
		
		private System.Nullable<decimal> _est_plan_prior;
		
		private System.Nullable<decimal> _est_plan_rev;
		
		private string _component_nbr_legacy;
		
		private string _flood_2006;
		
		private string _fk_bmpStatus2006_code;
		
		private System.Nullable<int> _fk_farmBusiness_implementation_transferred_from;
		
		private System.Nullable<byte> _QualifierVersion;
		
		private string _fk_procurementType_code;
		
		private string _bid_nbr_legacy;
		
		private System.Nullable<decimal> _design_cost;
		
		private System.Nullable<decimal> _final_modifications_cost;
		
		private System.Nullable<decimal> _final_cost;
		
		private string _fk_statusBMP_code;
		
		private System.Nullable<int> _fk_list_designerEngineer_engineer;
		
		private System.Nullable<int> _fk_list_designerEngineer_planner;
		
		private string _fk_agency_code_tech;
		
		private string _fk_revisionDescription_code;
		
		private string _revisionDescription_addl;
		
		private System.Nullable<System.DateTime> _created;
		
		private string _created_by;
		
		private string _bmp_id_new_legacy;
		
		private string _CREP;
		
		private string _includeOnWFP2;
		
		private System.Nullable<int> _fk_farmBusiness_implementation_transferred_to;
		
		private System.Nullable<int> _fk_list_designerEngineer_certifier;
		
		private System.Nullable<int> _fk_list_designerEngineer_inspector;
		
		private System.Nullable<System.DateTime> _modified;
		
		private string _modified_by;
		
		private System.Nullable<int> _fk_form_wfp2_version;
		
		private string _supplementalAttachmentWFP2;
		
		private System.Nullable<decimal> _wac_appr_amt_orig_legacy;
		
		private System.Nullable<System.DateTime> _completed_date;
		
		private string _AWEP;
		
		private string _EQIP;
		
		private System.Nullable<decimal> _ABC;
		
		private string _validForABCCalc;
		
		private string _dimensions;
		
		private System.Nullable<decimal> _unit_est_planned_ro;
		
		private System.Nullable<int> _fk_programmaticRecord_code;
		
		private string _landowner_contribution;
		
		private string _fk_BMPSource_code;
		
		private System.Nullable<decimal> _units_completed;
		
		private string _fk_SAAssignType_code;
		
		private System.Nullable<int> _fk_supplementalAgreementTaxParcel;
		
		private string _description_short;
		
		private System.Nullable<int> _fk_bmp_ag_ancestor;
		
		private System.Nullable<int> _fk_bmp_ag_transferredTo;
		
		private System.Nullable<int> _fk_bmp_ag_transferredFrom;
		
		private string _SAStr_ro;
		
		private string _SATPStr_ro;
		
		private System.Nullable<decimal> _units_designed;
		
		private string _dimensions_designed;
		
		private string _fk_BMPSortGroup_code;
		
		private string _issueStatement_wfp2;
		
		private string _fk_BMPCode_code;
		
		private string _fk_BMPCREPH20_code;
		
		private System.Nullable<int> _fk_bmp_ag_subIssueHeader;
		
		private System.Nullable<short> _NMCP_yr;
		
		private string _TaxParcels;
		
		private System.Nullable<int> _fk_farmBusinessWLProject;
		
		private string _Bmp;
		
		private string _CompositBmpNum;
		
		private EntityRef<bmp_ag> _bmp_ag2;
		
		private EntitySet<bmp_ag> _bmp_ags;
		
		private EntitySet<bmp_ag> _bmp_ags1;
		
		private EntitySet<bmp_ag> _bmp_ags2;
		
		private EntitySet<bmp_ag> _bmp_ags3;
		
		private EntityRef<bmp_ag> _bmp_ag1;
		
		private EntityRef<bmp_ag> _bmp_ag3;
		
		private EntityRef<bmp_ag> _bmp_ag4;
		
		private EntityRef<bmp_ag> _bmp_ag5;
		
		private EntityRef<bmp_ag> _bmp_ag6;
		
		private EntityRef<list_BMPCode> _list_BMPCode;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_bmp_agChanging(int value);
    partial void Onpk_bmp_agChanged();
    partial void Onfk_farmBusinessChanging(int value);
    partial void Onfk_farmBusinessChanged();
    partial void Onfk_pollutant_category_codeChanging(string value);
    partial void Onfk_pollutant_category_codeChanged();
    partial void Onbmp_nbrChanging(string value);
    partial void Onbmp_nbrChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    partial void Onlifespan_yearChanging(System.Nullable<byte> value);
    partial void Onlifespan_yearChanged();
    partial void Onfk_bmpPractice_codeChanging(System.Nullable<decimal> value);
    partial void Onfk_bmpPractice_codeChanged();
    partial void OnlocationChanging(string value);
    partial void OnlocationChanged();
    partial void Onunits_plannedChanging(System.Nullable<decimal> value);
    partial void Onunits_plannedChanged();
    partial void Onfk_unit_codeChanging(string value);
    partial void Onfk_unit_codeChanged();
    partial void Onest_plan_priorChanging(System.Nullable<decimal> value);
    partial void Onest_plan_priorChanged();
    partial void Onest_plan_revChanging(System.Nullable<decimal> value);
    partial void Onest_plan_revChanged();
    partial void Oncomponent_nbr_legacyChanging(string value);
    partial void Oncomponent_nbr_legacyChanged();
    partial void Onflood_2006Changing(string value);
    partial void Onflood_2006Changed();
    partial void Onfk_bmpStatus2006_codeChanging(string value);
    partial void Onfk_bmpStatus2006_codeChanged();
    partial void Onfk_farmBusiness_implementation_transferred_fromChanging(System.Nullable<int> value);
    partial void Onfk_farmBusiness_implementation_transferred_fromChanged();
    partial void OnQualifierVersionChanging(System.Nullable<byte> value);
    partial void OnQualifierVersionChanged();
    partial void Onfk_procurementType_codeChanging(string value);
    partial void Onfk_procurementType_codeChanged();
    partial void Onbid_nbr_legacyChanging(string value);
    partial void Onbid_nbr_legacyChanged();
    partial void Ondesign_costChanging(System.Nullable<decimal> value);
    partial void Ondesign_costChanged();
    partial void Onfinal_modifications_costChanging(System.Nullable<decimal> value);
    partial void Onfinal_modifications_costChanged();
    partial void Onfinal_costChanging(System.Nullable<decimal> value);
    partial void Onfinal_costChanged();
    partial void Onfk_statusBMP_codeChanging(string value);
    partial void Onfk_statusBMP_codeChanged();
    partial void Onfk_list_designerEngineer_engineerChanging(System.Nullable<int> value);
    partial void Onfk_list_designerEngineer_engineerChanged();
    partial void Onfk_list_designerEngineer_plannerChanging(System.Nullable<int> value);
    partial void Onfk_list_designerEngineer_plannerChanged();
    partial void Onfk_agency_code_techChanging(string value);
    partial void Onfk_agency_code_techChanged();
    partial void Onfk_revisionDescription_codeChanging(string value);
    partial void Onfk_revisionDescription_codeChanged();
    partial void OnrevisionDescription_addlChanging(string value);
    partial void OnrevisionDescription_addlChanged();
    partial void OncreatedChanging(System.Nullable<System.DateTime> value);
    partial void OncreatedChanged();
    partial void Oncreated_byChanging(string value);
    partial void Oncreated_byChanged();
    partial void Onbmp_id_new_legacyChanging(string value);
    partial void Onbmp_id_new_legacyChanged();
    partial void OnCREPChanging(string value);
    partial void OnCREPChanged();
    partial void OnincludeOnWFP2Changing(string value);
    partial void OnincludeOnWFP2Changed();
    partial void Onfk_farmBusiness_implementation_transferred_toChanging(System.Nullable<int> value);
    partial void Onfk_farmBusiness_implementation_transferred_toChanged();
    partial void Onfk_list_designerEngineer_certifierChanging(System.Nullable<int> value);
    partial void Onfk_list_designerEngineer_certifierChanged();
    partial void Onfk_list_designerEngineer_inspectorChanging(System.Nullable<int> value);
    partial void Onfk_list_designerEngineer_inspectorChanged();
    partial void OnmodifiedChanging(System.Nullable<System.DateTime> value);
    partial void OnmodifiedChanged();
    partial void Onmodified_byChanging(string value);
    partial void Onmodified_byChanged();
    partial void Onfk_form_wfp2_versionChanging(System.Nullable<int> value);
    partial void Onfk_form_wfp2_versionChanged();
    partial void OnsupplementalAttachmentWFP2Changing(string value);
    partial void OnsupplementalAttachmentWFP2Changed();
    partial void Onwac_appr_amt_orig_legacyChanging(System.Nullable<decimal> value);
    partial void Onwac_appr_amt_orig_legacyChanged();
    partial void Oncompleted_dateChanging(System.Nullable<System.DateTime> value);
    partial void Oncompleted_dateChanged();
    partial void OnAWEPChanging(string value);
    partial void OnAWEPChanged();
    partial void OnEQIPChanging(string value);
    partial void OnEQIPChanged();
    partial void OnABCChanging(System.Nullable<decimal> value);
    partial void OnABCChanged();
    partial void OnvalidForABCCalcChanging(string value);
    partial void OnvalidForABCCalcChanged();
    partial void OndimensionsChanging(string value);
    partial void OndimensionsChanged();
    partial void Onunit_est_planned_roChanging(System.Nullable<decimal> value);
    partial void Onunit_est_planned_roChanged();
    partial void Onfk_programmaticRecord_codeChanging(System.Nullable<int> value);
    partial void Onfk_programmaticRecord_codeChanged();
    partial void Onlandowner_contributionChanging(string value);
    partial void Onlandowner_contributionChanged();
    partial void Onfk_BMPSource_codeChanging(string value);
    partial void Onfk_BMPSource_codeChanged();
    partial void Onunits_completedChanging(System.Nullable<decimal> value);
    partial void Onunits_completedChanged();
    partial void Onfk_SAAssignType_codeChanging(string value);
    partial void Onfk_SAAssignType_codeChanged();
    partial void Onfk_supplementalAgreementTaxParcelChanging(System.Nullable<int> value);
    partial void Onfk_supplementalAgreementTaxParcelChanged();
    partial void Ondescription_shortChanging(string value);
    partial void Ondescription_shortChanged();
    partial void Onfk_bmp_ag_ancestorChanging(System.Nullable<int> value);
    partial void Onfk_bmp_ag_ancestorChanged();
    partial void Onfk_bmp_ag_transferredToChanging(System.Nullable<int> value);
    partial void Onfk_bmp_ag_transferredToChanged();
    partial void Onfk_bmp_ag_transferredFromChanging(System.Nullable<int> value);
    partial void Onfk_bmp_ag_transferredFromChanged();
    partial void OnSAStr_roChanging(string value);
    partial void OnSAStr_roChanged();
    partial void OnSATPStr_roChanging(string value);
    partial void OnSATPStr_roChanged();
    partial void Onunits_designedChanging(System.Nullable<decimal> value);
    partial void Onunits_designedChanged();
    partial void Ondimensions_designedChanging(string value);
    partial void Ondimensions_designedChanged();
    partial void Onfk_BMPSortGroup_codeChanging(string value);
    partial void Onfk_BMPSortGroup_codeChanged();
    partial void OnissueStatement_wfp2Changing(string value);
    partial void OnissueStatement_wfp2Changed();
    partial void Onfk_BMPCode_codeChanging(string value);
    partial void Onfk_BMPCode_codeChanged();
    partial void Onfk_BMPCREPH20_codeChanging(string value);
    partial void Onfk_BMPCREPH20_codeChanged();
    partial void Onfk_bmp_ag_subIssueHeaderChanging(System.Nullable<int> value);
    partial void Onfk_bmp_ag_subIssueHeaderChanged();
    partial void OnNMCP_yrChanging(System.Nullable<short> value);
    partial void OnNMCP_yrChanged();
    partial void OnTaxParcelsChanging(string value);
    partial void OnTaxParcelsChanged();
    partial void Onfk_farmBusinessWLProjectChanging(System.Nullable<int> value);
    partial void Onfk_farmBusinessWLProjectChanged();
    partial void OnBmpChanging(string value);
    partial void OnBmpChanged();
    partial void OnCompositBmpNumChanging(string value);
    partial void OnCompositBmpNumChanged();
    #endregion
		
		public bmp_ag()
		{
			this._bmp_ag2 = default(EntityRef<bmp_ag>);
			this._bmp_ags = new EntitySet<bmp_ag>(new Action<bmp_ag>(this.attach_bmp_ags), new Action<bmp_ag>(this.detach_bmp_ags));
			this._bmp_ags1 = new EntitySet<bmp_ag>(new Action<bmp_ag>(this.attach_bmp_ags1), new Action<bmp_ag>(this.detach_bmp_ags1));
			this._bmp_ags2 = new EntitySet<bmp_ag>(new Action<bmp_ag>(this.attach_bmp_ags2), new Action<bmp_ag>(this.detach_bmp_ags2));
			this._bmp_ags3 = new EntitySet<bmp_ag>(new Action<bmp_ag>(this.attach_bmp_ags3), new Action<bmp_ag>(this.detach_bmp_ags3));
			this._bmp_ag1 = default(EntityRef<bmp_ag>);
			this._bmp_ag3 = default(EntityRef<bmp_ag>);
			this._bmp_ag4 = default(EntityRef<bmp_ag>);
			this._bmp_ag5 = default(EntityRef<bmp_ag>);
			this._bmp_ag6 = default(EntityRef<bmp_ag>);
			this._list_BMPCode = default(EntityRef<list_BMPCode>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_bmp_ag", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pk_bmp_ag
		{
			get
			{
				return this._pk_bmp_ag;
			}
			set
			{
				if ((this._pk_bmp_ag != value))
				{
					if (this._bmp_ag1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onpk_bmp_agChanging(value);
					this.SendPropertyChanging();
					this._pk_bmp_ag = value;
					this.SendPropertyChanged("pk_bmp_ag");
					this.Onpk_bmp_agChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_farmBusiness", DbType="Int NOT NULL")]
		public int fk_farmBusiness
		{
			get
			{
				return this._fk_farmBusiness;
			}
			set
			{
				if ((this._fk_farmBusiness != value))
				{
					this.Onfk_farmBusinessChanging(value);
					this.SendPropertyChanging();
					this._fk_farmBusiness = value;
					this.SendPropertyChanged("fk_farmBusiness");
					this.Onfk_farmBusinessChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_pollutant_category_code", DbType="NVarChar(16) NOT NULL", CanBeNull=false)]
		public string fk_pollutant_category_code
		{
			get
			{
				return this._fk_pollutant_category_code;
			}
			set
			{
				if ((this._fk_pollutant_category_code != value))
				{
					this.Onfk_pollutant_category_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_pollutant_category_code = value;
					this.SendPropertyChanged("fk_pollutant_category_code");
					this.Onfk_pollutant_category_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bmp_nbr", DbType="NVarChar(24)")]
		public string bmp_nbr
		{
			get
			{
				return this._bmp_nbr;
			}
			set
			{
				if ((this._bmp_nbr != value))
				{
					this.Onbmp_nbrChanging(value);
					this.SendPropertyChanging();
					this._bmp_nbr = value;
					this.SendPropertyChanged("bmp_nbr");
					this.Onbmp_nbrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="NVarChar(400)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lifespan_year", DbType="TinyInt")]
		public System.Nullable<byte> lifespan_year
		{
			get
			{
				return this._lifespan_year;
			}
			set
			{
				if ((this._lifespan_year != value))
				{
					this.Onlifespan_yearChanging(value);
					this.SendPropertyChanging();
					this._lifespan_year = value;
					this.SendPropertyChanged("lifespan_year");
					this.Onlifespan_yearChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmpPractice_code", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> fk_bmpPractice_code
		{
			get
			{
				return this._fk_bmpPractice_code;
			}
			set
			{
				if ((this._fk_bmpPractice_code != value))
				{
					this.Onfk_bmpPractice_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_bmpPractice_code = value;
					this.SendPropertyChanged("fk_bmpPractice_code");
					this.Onfk_bmpPractice_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_location", DbType="NVarChar(96)")]
		public string location
		{
			get
			{
				return this._location;
			}
			set
			{
				if ((this._location != value))
				{
					this.OnlocationChanging(value);
					this.SendPropertyChanging();
					this._location = value;
					this.SendPropertyChanged("location");
					this.OnlocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_units_planned", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> units_planned
		{
			get
			{
				return this._units_planned;
			}
			set
			{
				if ((this._units_planned != value))
				{
					this.Onunits_plannedChanging(value);
					this.SendPropertyChanging();
					this._units_planned = value;
					this.SendPropertyChanged("units_planned");
					this.Onunits_plannedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_unit_code", DbType="NVarChar(8)")]
		public string fk_unit_code
		{
			get
			{
				return this._fk_unit_code;
			}
			set
			{
				if ((this._fk_unit_code != value))
				{
					this.Onfk_unit_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_unit_code = value;
					this.SendPropertyChanged("fk_unit_code");
					this.Onfk_unit_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_plan_prior", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> est_plan_prior
		{
			get
			{
				return this._est_plan_prior;
			}
			set
			{
				if ((this._est_plan_prior != value))
				{
					this.Onest_plan_priorChanging(value);
					this.SendPropertyChanging();
					this._est_plan_prior = value;
					this.SendPropertyChanged("est_plan_prior");
					this.Onest_plan_priorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_est_plan_rev", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> est_plan_rev
		{
			get
			{
				return this._est_plan_rev;
			}
			set
			{
				if ((this._est_plan_rev != value))
				{
					this.Onest_plan_revChanging(value);
					this.SendPropertyChanging();
					this._est_plan_rev = value;
					this.SendPropertyChanged("est_plan_rev");
					this.Onest_plan_revChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_component_nbr_legacy", DbType="NVarChar(12)")]
		public string component_nbr_legacy
		{
			get
			{
				return this._component_nbr_legacy;
			}
			set
			{
				if ((this._component_nbr_legacy != value))
				{
					this.Oncomponent_nbr_legacyChanging(value);
					this.SendPropertyChanging();
					this._component_nbr_legacy = value;
					this.SendPropertyChanged("component_nbr_legacy");
					this.Oncomponent_nbr_legacyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_flood_2006", DbType="NVarChar(1)")]
		public string flood_2006
		{
			get
			{
				return this._flood_2006;
			}
			set
			{
				if ((this._flood_2006 != value))
				{
					this.Onflood_2006Changing(value);
					this.SendPropertyChanging();
					this._flood_2006 = value;
					this.SendPropertyChanged("flood_2006");
					this.Onflood_2006Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmpStatus2006_code", DbType="NVarChar(8)")]
		public string fk_bmpStatus2006_code
		{
			get
			{
				return this._fk_bmpStatus2006_code;
			}
			set
			{
				if ((this._fk_bmpStatus2006_code != value))
				{
					this.Onfk_bmpStatus2006_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_bmpStatus2006_code = value;
					this.SendPropertyChanged("fk_bmpStatus2006_code");
					this.Onfk_bmpStatus2006_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_farmBusiness_implementation_transferred_from", DbType="Int")]
		public System.Nullable<int> fk_farmBusiness_implementation_transferred_from
		{
			get
			{
				return this._fk_farmBusiness_implementation_transferred_from;
			}
			set
			{
				if ((this._fk_farmBusiness_implementation_transferred_from != value))
				{
					this.Onfk_farmBusiness_implementation_transferred_fromChanging(value);
					this.SendPropertyChanging();
					this._fk_farmBusiness_implementation_transferred_from = value;
					this.SendPropertyChanged("fk_farmBusiness_implementation_transferred_from");
					this.Onfk_farmBusiness_implementation_transferred_fromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_QualifierVersion", DbType="TinyInt")]
		public System.Nullable<byte> QualifierVersion
		{
			get
			{
				return this._QualifierVersion;
			}
			set
			{
				if ((this._QualifierVersion != value))
				{
					this.OnQualifierVersionChanging(value);
					this.SendPropertyChanging();
					this._QualifierVersion = value;
					this.SendPropertyChanged("QualifierVersion");
					this.OnQualifierVersionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_procurementType_code", DbType="NVarChar(2)")]
		public string fk_procurementType_code
		{
			get
			{
				return this._fk_procurementType_code;
			}
			set
			{
				if ((this._fk_procurementType_code != value))
				{
					this.Onfk_procurementType_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_procurementType_code = value;
					this.SendPropertyChanged("fk_procurementType_code");
					this.Onfk_procurementType_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bid_nbr_legacy", DbType="NVarChar(16)")]
		public string bid_nbr_legacy
		{
			get
			{
				return this._bid_nbr_legacy;
			}
			set
			{
				if ((this._bid_nbr_legacy != value))
				{
					this.Onbid_nbr_legacyChanging(value);
					this.SendPropertyChanging();
					this._bid_nbr_legacy = value;
					this.SendPropertyChanged("bid_nbr_legacy");
					this.Onbid_nbr_legacyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_design_cost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> design_cost
		{
			get
			{
				return this._design_cost;
			}
			set
			{
				if ((this._design_cost != value))
				{
					this.Ondesign_costChanging(value);
					this.SendPropertyChanging();
					this._design_cost = value;
					this.SendPropertyChanged("design_cost");
					this.Ondesign_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_modifications_cost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> final_modifications_cost
		{
			get
			{
				return this._final_modifications_cost;
			}
			set
			{
				if ((this._final_modifications_cost != value))
				{
					this.Onfinal_modifications_costChanging(value);
					this.SendPropertyChanging();
					this._final_modifications_cost = value;
					this.SendPropertyChanged("final_modifications_cost");
					this.Onfinal_modifications_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_final_cost", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> final_cost
		{
			get
			{
				return this._final_cost;
			}
			set
			{
				if ((this._final_cost != value))
				{
					this.Onfinal_costChanging(value);
					this.SendPropertyChanging();
					this._final_cost = value;
					this.SendPropertyChanged("final_cost");
					this.Onfinal_costChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_statusBMP_code", DbType="NVarChar(8)")]
		public string fk_statusBMP_code
		{
			get
			{
				return this._fk_statusBMP_code;
			}
			set
			{
				if ((this._fk_statusBMP_code != value))
				{
					this.Onfk_statusBMP_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_statusBMP_code = value;
					this.SendPropertyChanged("fk_statusBMP_code");
					this.Onfk_statusBMP_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_list_designerEngineer_engineer", DbType="Int")]
		public System.Nullable<int> fk_list_designerEngineer_engineer
		{
			get
			{
				return this._fk_list_designerEngineer_engineer;
			}
			set
			{
				if ((this._fk_list_designerEngineer_engineer != value))
				{
					this.Onfk_list_designerEngineer_engineerChanging(value);
					this.SendPropertyChanging();
					this._fk_list_designerEngineer_engineer = value;
					this.SendPropertyChanged("fk_list_designerEngineer_engineer");
					this.Onfk_list_designerEngineer_engineerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_list_designerEngineer_planner", DbType="Int")]
		public System.Nullable<int> fk_list_designerEngineer_planner
		{
			get
			{
				return this._fk_list_designerEngineer_planner;
			}
			set
			{
				if ((this._fk_list_designerEngineer_planner != value))
				{
					this.Onfk_list_designerEngineer_plannerChanging(value);
					this.SendPropertyChanging();
					this._fk_list_designerEngineer_planner = value;
					this.SendPropertyChanged("fk_list_designerEngineer_planner");
					this.Onfk_list_designerEngineer_plannerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_agency_code_tech", DbType="NVarChar(16)")]
		public string fk_agency_code_tech
		{
			get
			{
				return this._fk_agency_code_tech;
			}
			set
			{
				if ((this._fk_agency_code_tech != value))
				{
					this.Onfk_agency_code_techChanging(value);
					this.SendPropertyChanging();
					this._fk_agency_code_tech = value;
					this.SendPropertyChanged("fk_agency_code_tech");
					this.Onfk_agency_code_techChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_revisionDescription_code", DbType="NVarChar(16)")]
		public string fk_revisionDescription_code
		{
			get
			{
				return this._fk_revisionDescription_code;
			}
			set
			{
				if ((this._fk_revisionDescription_code != value))
				{
					this.Onfk_revisionDescription_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_revisionDescription_code = value;
					this.SendPropertyChanged("fk_revisionDescription_code");
					this.Onfk_revisionDescription_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_revisionDescription_addl", DbType="NVarChar(48)")]
		public string revisionDescription_addl
		{
			get
			{
				return this._revisionDescription_addl;
			}
			set
			{
				if ((this._revisionDescription_addl != value))
				{
					this.OnrevisionDescription_addlChanging(value);
					this.SendPropertyChanging();
					this._revisionDescription_addl = value;
					this.SendPropertyChanged("revisionDescription_addl");
					this.OnrevisionDescription_addlChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created", DbType="DateTime")]
		public System.Nullable<System.DateTime> created
		{
			get
			{
				return this._created;
			}
			set
			{
				if ((this._created != value))
				{
					this.OncreatedChanging(value);
					this.SendPropertyChanging();
					this._created = value;
					this.SendPropertyChanged("created");
					this.OncreatedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_created_by", DbType="NVarChar(36)")]
		public string created_by
		{
			get
			{
				return this._created_by;
			}
			set
			{
				if ((this._created_by != value))
				{
					this.Oncreated_byChanging(value);
					this.SendPropertyChanging();
					this._created_by = value;
					this.SendPropertyChanged("created_by");
					this.Oncreated_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_bmp_id_new_legacy", DbType="NVarChar(20)")]
		public string bmp_id_new_legacy
		{
			get
			{
				return this._bmp_id_new_legacy;
			}
			set
			{
				if ((this._bmp_id_new_legacy != value))
				{
					this.Onbmp_id_new_legacyChanging(value);
					this.SendPropertyChanging();
					this._bmp_id_new_legacy = value;
					this.SendPropertyChanged("bmp_id_new_legacy");
					this.Onbmp_id_new_legacyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREP", DbType="NVarChar(1)")]
		public string CREP
		{
			get
			{
				return this._CREP;
			}
			set
			{
				if ((this._CREP != value))
				{
					this.OnCREPChanging(value);
					this.SendPropertyChanging();
					this._CREP = value;
					this.SendPropertyChanged("CREP");
					this.OnCREPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_includeOnWFP2", DbType="NVarChar(1)")]
		public string includeOnWFP2
		{
			get
			{
				return this._includeOnWFP2;
			}
			set
			{
				if ((this._includeOnWFP2 != value))
				{
					this.OnincludeOnWFP2Changing(value);
					this.SendPropertyChanging();
					this._includeOnWFP2 = value;
					this.SendPropertyChanged("includeOnWFP2");
					this.OnincludeOnWFP2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_farmBusiness_implementation_transferred_to", DbType="Int")]
		public System.Nullable<int> fk_farmBusiness_implementation_transferred_to
		{
			get
			{
				return this._fk_farmBusiness_implementation_transferred_to;
			}
			set
			{
				if ((this._fk_farmBusiness_implementation_transferred_to != value))
				{
					this.Onfk_farmBusiness_implementation_transferred_toChanging(value);
					this.SendPropertyChanging();
					this._fk_farmBusiness_implementation_transferred_to = value;
					this.SendPropertyChanged("fk_farmBusiness_implementation_transferred_to");
					this.Onfk_farmBusiness_implementation_transferred_toChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_list_designerEngineer_certifier", DbType="Int")]
		public System.Nullable<int> fk_list_designerEngineer_certifier
		{
			get
			{
				return this._fk_list_designerEngineer_certifier;
			}
			set
			{
				if ((this._fk_list_designerEngineer_certifier != value))
				{
					this.Onfk_list_designerEngineer_certifierChanging(value);
					this.SendPropertyChanging();
					this._fk_list_designerEngineer_certifier = value;
					this.SendPropertyChanged("fk_list_designerEngineer_certifier");
					this.Onfk_list_designerEngineer_certifierChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_list_designerEngineer_inspector", DbType="Int")]
		public System.Nullable<int> fk_list_designerEngineer_inspector
		{
			get
			{
				return this._fk_list_designerEngineer_inspector;
			}
			set
			{
				if ((this._fk_list_designerEngineer_inspector != value))
				{
					this.Onfk_list_designerEngineer_inspectorChanging(value);
					this.SendPropertyChanging();
					this._fk_list_designerEngineer_inspector = value;
					this.SendPropertyChanged("fk_list_designerEngineer_inspector");
					this.Onfk_list_designerEngineer_inspectorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified", DbType="DateTime")]
		public System.Nullable<System.DateTime> modified
		{
			get
			{
				return this._modified;
			}
			set
			{
				if ((this._modified != value))
				{
					this.OnmodifiedChanging(value);
					this.SendPropertyChanging();
					this._modified = value;
					this.SendPropertyChanged("modified");
					this.OnmodifiedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_modified_by", DbType="NVarChar(36)")]
		public string modified_by
		{
			get
			{
				return this._modified_by;
			}
			set
			{
				if ((this._modified_by != value))
				{
					this.Onmodified_byChanging(value);
					this.SendPropertyChanging();
					this._modified_by = value;
					this.SendPropertyChanged("modified_by");
					this.Onmodified_byChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_form_wfp2_version", DbType="Int")]
		public System.Nullable<int> fk_form_wfp2_version
		{
			get
			{
				return this._fk_form_wfp2_version;
			}
			set
			{
				if ((this._fk_form_wfp2_version != value))
				{
					this.Onfk_form_wfp2_versionChanging(value);
					this.SendPropertyChanging();
					this._fk_form_wfp2_version = value;
					this.SendPropertyChanged("fk_form_wfp2_version");
					this.Onfk_form_wfp2_versionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_supplementalAttachmentWFP2", DbType="NVarChar(1)")]
		public string supplementalAttachmentWFP2
		{
			get
			{
				return this._supplementalAttachmentWFP2;
			}
			set
			{
				if ((this._supplementalAttachmentWFP2 != value))
				{
					this.OnsupplementalAttachmentWFP2Changing(value);
					this.SendPropertyChanging();
					this._supplementalAttachmentWFP2 = value;
					this.SendPropertyChanged("supplementalAttachmentWFP2");
					this.OnsupplementalAttachmentWFP2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_wac_appr_amt_orig_legacy", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> wac_appr_amt_orig_legacy
		{
			get
			{
				return this._wac_appr_amt_orig_legacy;
			}
			set
			{
				if ((this._wac_appr_amt_orig_legacy != value))
				{
					this.Onwac_appr_amt_orig_legacyChanging(value);
					this.SendPropertyChanging();
					this._wac_appr_amt_orig_legacy = value;
					this.SendPropertyChanged("wac_appr_amt_orig_legacy");
					this.Onwac_appr_amt_orig_legacyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_completed_date", DbType="DateTime")]
		public System.Nullable<System.DateTime> completed_date
		{
			get
			{
				return this._completed_date;
			}
			set
			{
				if ((this._completed_date != value))
				{
					this.Oncompleted_dateChanging(value);
					this.SendPropertyChanging();
					this._completed_date = value;
					this.SendPropertyChanged("completed_date");
					this.Oncompleted_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWEP", DbType="NVarChar(1)")]
		public string AWEP
		{
			get
			{
				return this._AWEP;
			}
			set
			{
				if ((this._AWEP != value))
				{
					this.OnAWEPChanging(value);
					this.SendPropertyChanging();
					this._AWEP = value;
					this.SendPropertyChanged("AWEP");
					this.OnAWEPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EQIP", DbType="NVarChar(1)")]
		public string EQIP
		{
			get
			{
				return this._EQIP;
			}
			set
			{
				if ((this._EQIP != value))
				{
					this.OnEQIPChanging(value);
					this.SendPropertyChanging();
					this._EQIP = value;
					this.SendPropertyChanged("EQIP");
					this.OnEQIPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABC", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> ABC
		{
			get
			{
				return this._ABC;
			}
			set
			{
				if ((this._ABC != value))
				{
					this.OnABCChanging(value);
					this.SendPropertyChanging();
					this._ABC = value;
					this.SendPropertyChanged("ABC");
					this.OnABCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_validForABCCalc", DbType="NVarChar(1)")]
		public string validForABCCalc
		{
			get
			{
				return this._validForABCCalc;
			}
			set
			{
				if ((this._validForABCCalc != value))
				{
					this.OnvalidForABCCalcChanging(value);
					this.SendPropertyChanging();
					this._validForABCCalc = value;
					this.SendPropertyChanged("validForABCCalc");
					this.OnvalidForABCCalcChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dimensions", DbType="NVarChar(48)")]
		public string dimensions
		{
			get
			{
				return this._dimensions;
			}
			set
			{
				if ((this._dimensions != value))
				{
					this.OndimensionsChanging(value);
					this.SendPropertyChanging();
					this._dimensions = value;
					this.SendPropertyChanged("dimensions");
					this.OndimensionsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_unit_est_planned_ro", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> unit_est_planned_ro
		{
			get
			{
				return this._unit_est_planned_ro;
			}
			set
			{
				if ((this._unit_est_planned_ro != value))
				{
					this.Onunit_est_planned_roChanging(value);
					this.SendPropertyChanging();
					this._unit_est_planned_ro = value;
					this.SendPropertyChanged("unit_est_planned_ro");
					this.Onunit_est_planned_roChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_programmaticRecord_code", DbType="Int")]
		public System.Nullable<int> fk_programmaticRecord_code
		{
			get
			{
				return this._fk_programmaticRecord_code;
			}
			set
			{
				if ((this._fk_programmaticRecord_code != value))
				{
					this.Onfk_programmaticRecord_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_programmaticRecord_code = value;
					this.SendPropertyChanged("fk_programmaticRecord_code");
					this.Onfk_programmaticRecord_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_landowner_contribution", DbType="NVarChar(1)")]
		public string landowner_contribution
		{
			get
			{
				return this._landowner_contribution;
			}
			set
			{
				if ((this._landowner_contribution != value))
				{
					this.Onlandowner_contributionChanging(value);
					this.SendPropertyChanging();
					this._landowner_contribution = value;
					this.SendPropertyChanged("landowner_contribution");
					this.Onlandowner_contributionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_BMPSource_code", DbType="NVarChar(1) NOT NULL", CanBeNull=false)]
		public string fk_BMPSource_code
		{
			get
			{
				return this._fk_BMPSource_code;
			}
			set
			{
				if ((this._fk_BMPSource_code != value))
				{
					this.Onfk_BMPSource_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_BMPSource_code = value;
					this.SendPropertyChanged("fk_BMPSource_code");
					this.Onfk_BMPSource_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_units_completed", DbType="Decimal(10,2)")]
		public System.Nullable<decimal> units_completed
		{
			get
			{
				return this._units_completed;
			}
			set
			{
				if ((this._units_completed != value))
				{
					this.Onunits_completedChanging(value);
					this.SendPropertyChanging();
					this._units_completed = value;
					this.SendPropertyChanged("units_completed");
					this.Onunits_completedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_SAAssignType_code", DbType="NVarChar(1)")]
		public string fk_SAAssignType_code
		{
			get
			{
				return this._fk_SAAssignType_code;
			}
			set
			{
				if ((this._fk_SAAssignType_code != value))
				{
					this.Onfk_SAAssignType_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_SAAssignType_code = value;
					this.SendPropertyChanged("fk_SAAssignType_code");
					this.Onfk_SAAssignType_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_supplementalAgreementTaxParcel", DbType="Int")]
		public System.Nullable<int> fk_supplementalAgreementTaxParcel
		{
			get
			{
				return this._fk_supplementalAgreementTaxParcel;
			}
			set
			{
				if ((this._fk_supplementalAgreementTaxParcel != value))
				{
					this.Onfk_supplementalAgreementTaxParcelChanging(value);
					this.SendPropertyChanging();
					this._fk_supplementalAgreementTaxParcel = value;
					this.SendPropertyChanged("fk_supplementalAgreementTaxParcel");
					this.Onfk_supplementalAgreementTaxParcelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description_short", DbType="NVarChar(255)")]
		public string description_short
		{
			get
			{
				return this._description_short;
			}
			set
			{
				if ((this._description_short != value))
				{
					this.Ondescription_shortChanging(value);
					this.SendPropertyChanging();
					this._description_short = value;
					this.SendPropertyChanged("description_short");
					this.Ondescription_shortChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmp_ag_ancestor", DbType="Int")]
		public System.Nullable<int> fk_bmp_ag_ancestor
		{
			get
			{
				return this._fk_bmp_ag_ancestor;
			}
			set
			{
				if ((this._fk_bmp_ag_ancestor != value))
				{
					if (this._bmp_ag3.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_bmp_ag_ancestorChanging(value);
					this.SendPropertyChanging();
					this._fk_bmp_ag_ancestor = value;
					this.SendPropertyChanged("fk_bmp_ag_ancestor");
					this.Onfk_bmp_ag_ancestorChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmp_ag_transferredTo", DbType="Int")]
		public System.Nullable<int> fk_bmp_ag_transferredTo
		{
			get
			{
				return this._fk_bmp_ag_transferredTo;
			}
			set
			{
				if ((this._fk_bmp_ag_transferredTo != value))
				{
					if (this._bmp_ag6.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_bmp_ag_transferredToChanging(value);
					this.SendPropertyChanging();
					this._fk_bmp_ag_transferredTo = value;
					this.SendPropertyChanged("fk_bmp_ag_transferredTo");
					this.Onfk_bmp_ag_transferredToChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmp_ag_transferredFrom", DbType="Int")]
		public System.Nullable<int> fk_bmp_ag_transferredFrom
		{
			get
			{
				return this._fk_bmp_ag_transferredFrom;
			}
			set
			{
				if ((this._fk_bmp_ag_transferredFrom != value))
				{
					if (this._bmp_ag5.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_bmp_ag_transferredFromChanging(value);
					this.SendPropertyChanging();
					this._fk_bmp_ag_transferredFrom = value;
					this.SendPropertyChanged("fk_bmp_ag_transferredFrom");
					this.Onfk_bmp_ag_transferredFromChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SAStr_ro", DbType="NVarChar(255)")]
		public string SAStr_ro
		{
			get
			{
				return this._SAStr_ro;
			}
			set
			{
				if ((this._SAStr_ro != value))
				{
					this.OnSAStr_roChanging(value);
					this.SendPropertyChanging();
					this._SAStr_ro = value;
					this.SendPropertyChanged("SAStr_ro");
					this.OnSAStr_roChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SATPStr_ro", DbType="NVarChar(255)")]
		public string SATPStr_ro
		{
			get
			{
				return this._SATPStr_ro;
			}
			set
			{
				if ((this._SATPStr_ro != value))
				{
					this.OnSATPStr_roChanging(value);
					this.SendPropertyChanging();
					this._SATPStr_ro = value;
					this.SendPropertyChanged("SATPStr_ro");
					this.OnSATPStr_roChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_units_designed", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> units_designed
		{
			get
			{
				return this._units_designed;
			}
			set
			{
				if ((this._units_designed != value))
				{
					this.Onunits_designedChanging(value);
					this.SendPropertyChanging();
					this._units_designed = value;
					this.SendPropertyChanged("units_designed");
					this.Onunits_designedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dimensions_designed", DbType="NVarChar(48)")]
		public string dimensions_designed
		{
			get
			{
				return this._dimensions_designed;
			}
			set
			{
				if ((this._dimensions_designed != value))
				{
					this.Ondimensions_designedChanging(value);
					this.SendPropertyChanging();
					this._dimensions_designed = value;
					this.SendPropertyChanged("dimensions_designed");
					this.Ondimensions_designedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_BMPSortGroup_code", DbType="NVarChar(4)")]
		public string fk_BMPSortGroup_code
		{
			get
			{
				return this._fk_BMPSortGroup_code;
			}
			set
			{
				if ((this._fk_BMPSortGroup_code != value))
				{
					this.Onfk_BMPSortGroup_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_BMPSortGroup_code = value;
					this.SendPropertyChanged("fk_BMPSortGroup_code");
					this.Onfk_BMPSortGroup_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issueStatement_wfp2", DbType="NVarChar(1000)")]
		public string issueStatement_wfp2
		{
			get
			{
				return this._issueStatement_wfp2;
			}
			set
			{
				if ((this._issueStatement_wfp2 != value))
				{
					this.OnissueStatement_wfp2Changing(value);
					this.SendPropertyChanging();
					this._issueStatement_wfp2 = value;
					this.SendPropertyChanged("issueStatement_wfp2");
					this.OnissueStatement_wfp2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_BMPCode_code", DbType="NVarChar(8)")]
		public string fk_BMPCode_code
		{
			get
			{
				return this._fk_BMPCode_code;
			}
			set
			{
				if ((this._fk_BMPCode_code != value))
				{
					if (this._list_BMPCode.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_BMPCode_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_BMPCode_code = value;
					this.SendPropertyChanged("fk_BMPCode_code");
					this.Onfk_BMPCode_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_BMPCREPH20_code", DbType="NVarChar(2)")]
		public string fk_BMPCREPH20_code
		{
			get
			{
				return this._fk_BMPCREPH20_code;
			}
			set
			{
				if ((this._fk_BMPCREPH20_code != value))
				{
					this.Onfk_BMPCREPH20_codeChanging(value);
					this.SendPropertyChanging();
					this._fk_BMPCREPH20_code = value;
					this.SendPropertyChanged("fk_BMPCREPH20_code");
					this.Onfk_BMPCREPH20_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_bmp_ag_subIssueHeader", DbType="Int")]
		public System.Nullable<int> fk_bmp_ag_subIssueHeader
		{
			get
			{
				return this._fk_bmp_ag_subIssueHeader;
			}
			set
			{
				if ((this._fk_bmp_ag_subIssueHeader != value))
				{
					if (this._bmp_ag4.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onfk_bmp_ag_subIssueHeaderChanging(value);
					this.SendPropertyChanging();
					this._fk_bmp_ag_subIssueHeader = value;
					this.SendPropertyChanged("fk_bmp_ag_subIssueHeader");
					this.Onfk_bmp_ag_subIssueHeaderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NMCP_yr", DbType="SmallInt")]
		public System.Nullable<short> NMCP_yr
		{
			get
			{
				return this._NMCP_yr;
			}
			set
			{
				if ((this._NMCP_yr != value))
				{
					this.OnNMCP_yrChanging(value);
					this.SendPropertyChanging();
					this._NMCP_yr = value;
					this.SendPropertyChanged("NMCP_yr");
					this.OnNMCP_yrChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaxParcels", DbType="NChar(500)")]
		public string TaxParcels
		{
			get
			{
				return this._TaxParcels;
			}
			set
			{
				if ((this._TaxParcels != value))
				{
					this.OnTaxParcelsChanging(value);
					this.SendPropertyChanging();
					this._TaxParcels = value;
					this.SendPropertyChanged("TaxParcels");
					this.OnTaxParcelsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_farmBusinessWLProject", DbType="Int")]
		public System.Nullable<int> fk_farmBusinessWLProject
		{
			get
			{
				return this._fk_farmBusinessWLProject;
			}
			set
			{
				if ((this._fk_farmBusinessWLProject != value))
				{
					this.Onfk_farmBusinessWLProjectChanging(value);
					this.SendPropertyChanging();
					this._fk_farmBusinessWLProject = value;
					this.SendPropertyChanged("fk_farmBusinessWLProject");
					this.Onfk_farmBusinessWLProjectChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Bmp", DbType="NChar(10)")]
		public string Bmp
		{
			get
			{
				return this._Bmp;
			}
			set
			{
				if ((this._Bmp != value))
				{
					this.OnBmpChanging(value);
					this.SendPropertyChanging();
					this._Bmp = value;
					this.SendPropertyChanged("Bmp");
					this.OnBmpChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CompositBmpNum", AutoSync=AutoSync.Always, DbType="NVarChar(24)", IsDbGenerated=true, UpdateCheck=UpdateCheck.Never)]
		public string CompositBmpNum
		{
			get
			{
				return this._CompositBmpNum;
			}
			set
			{
				if ((this._CompositBmpNum != value))
				{
					this.OnCompositBmpNumChanging(value);
					this.SendPropertyChanging();
					this._CompositBmpNum = value;
					this.SendPropertyChanged("CompositBmpNum");
					this.OnCompositBmpNumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag", Storage="_bmp_ag2", ThisKey="pk_bmp_ag", OtherKey="pk_bmp_ag", IsUnique=true, IsForeignKey=false)]
		public bmp_ag bmp_ag2
		{
			get
			{
				return this._bmp_ag2.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag2.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag2.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag2.Entity = null;
						previousValue.bmp_ag1 = null;
					}
					this._bmp_ag2.Entity = value;
					if ((value != null))
					{
						value.bmp_ag1 = this;
					}
					this.SendPropertyChanged("bmp_ag2");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag1", Storage="_bmp_ags", ThisKey="pk_bmp_ag", OtherKey="fk_bmp_ag_ancestor")]
		public EntitySet<bmp_ag> bmp_ags
		{
			get
			{
				return this._bmp_ags;
			}
			set
			{
				this._bmp_ags.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag2", Storage="_bmp_ags1", ThisKey="pk_bmp_ag", OtherKey="fk_bmp_ag_subIssueHeader")]
		public EntitySet<bmp_ag> bmp_ags1
		{
			get
			{
				return this._bmp_ags1;
			}
			set
			{
				this._bmp_ags1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag3", Storage="_bmp_ags2", ThisKey="pk_bmp_ag", OtherKey="fk_bmp_ag_transferredFrom")]
		public EntitySet<bmp_ag> bmp_ags2
		{
			get
			{
				return this._bmp_ags2;
			}
			set
			{
				this._bmp_ags2.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag4", Storage="_bmp_ags3", ThisKey="pk_bmp_ag", OtherKey="fk_bmp_ag_transferredTo")]
		public EntitySet<bmp_ag> bmp_ags3
		{
			get
			{
				return this._bmp_ags3;
			}
			set
			{
				this._bmp_ags3.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag", Storage="_bmp_ag1", ThisKey="pk_bmp_ag", OtherKey="pk_bmp_ag", IsForeignKey=true)]
		public bmp_ag bmp_ag1
		{
			get
			{
				return this._bmp_ag1.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag1.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag1.Entity = null;
						previousValue.bmp_ag2 = null;
					}
					this._bmp_ag1.Entity = value;
					if ((value != null))
					{
						value.bmp_ag2 = this;
						this._pk_bmp_ag = value.pk_bmp_ag;
					}
					else
					{
						this._pk_bmp_ag = default(int);
					}
					this.SendPropertyChanged("bmp_ag1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag1", Storage="_bmp_ag3", ThisKey="fk_bmp_ag_ancestor", OtherKey="pk_bmp_ag", IsForeignKey=true)]
		public bmp_ag bmp_ag3
		{
			get
			{
				return this._bmp_ag3.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag3.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag3.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag3.Entity = null;
						previousValue.bmp_ags.Remove(this);
					}
					this._bmp_ag3.Entity = value;
					if ((value != null))
					{
						value.bmp_ags.Add(this);
						this._fk_bmp_ag_ancestor = value.pk_bmp_ag;
					}
					else
					{
						this._fk_bmp_ag_ancestor = default(Nullable<int>);
					}
					this.SendPropertyChanged("bmp_ag3");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag2", Storage="_bmp_ag4", ThisKey="fk_bmp_ag_subIssueHeader", OtherKey="pk_bmp_ag", IsForeignKey=true)]
		public bmp_ag bmp_ag4
		{
			get
			{
				return this._bmp_ag4.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag4.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag4.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag4.Entity = null;
						previousValue.bmp_ags1.Remove(this);
					}
					this._bmp_ag4.Entity = value;
					if ((value != null))
					{
						value.bmp_ags1.Add(this);
						this._fk_bmp_ag_subIssueHeader = value.pk_bmp_ag;
					}
					else
					{
						this._fk_bmp_ag_subIssueHeader = default(Nullable<int>);
					}
					this.SendPropertyChanged("bmp_ag4");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag3", Storage="_bmp_ag5", ThisKey="fk_bmp_ag_transferredFrom", OtherKey="pk_bmp_ag", IsForeignKey=true)]
		public bmp_ag bmp_ag5
		{
			get
			{
				return this._bmp_ag5.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag5.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag5.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag5.Entity = null;
						previousValue.bmp_ags2.Remove(this);
					}
					this._bmp_ag5.Entity = value;
					if ((value != null))
					{
						value.bmp_ags2.Add(this);
						this._fk_bmp_ag_transferredFrom = value.pk_bmp_ag;
					}
					else
					{
						this._fk_bmp_ag_transferredFrom = default(Nullable<int>);
					}
					this.SendPropertyChanged("bmp_ag5");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="bmp_ag_bmp_ag4", Storage="_bmp_ag6", ThisKey="fk_bmp_ag_transferredTo", OtherKey="pk_bmp_ag", IsForeignKey=true)]
		public bmp_ag bmp_ag6
		{
			get
			{
				return this._bmp_ag6.Entity;
			}
			set
			{
				bmp_ag previousValue = this._bmp_ag6.Entity;
				if (((previousValue != value) 
							|| (this._bmp_ag6.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._bmp_ag6.Entity = null;
						previousValue.bmp_ags3.Remove(this);
					}
					this._bmp_ag6.Entity = value;
					if ((value != null))
					{
						value.bmp_ags3.Add(this);
						this._fk_bmp_ag_transferredTo = value.pk_bmp_ag;
					}
					else
					{
						this._fk_bmp_ag_transferredTo = default(Nullable<int>);
					}
					this.SendPropertyChanged("bmp_ag6");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="list_BMPCode_bmp_ag", Storage="_list_BMPCode", ThisKey="fk_BMPCode_code", OtherKey="pk_BMPCode_code", IsForeignKey=true)]
		public list_BMPCode list_BMPCode
		{
			get
			{
				return this._list_BMPCode.Entity;
			}
			set
			{
				list_BMPCode previousValue = this._list_BMPCode.Entity;
				if (((previousValue != value) 
							|| (this._list_BMPCode.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._list_BMPCode.Entity = null;
						previousValue.bmp_ags.Remove(this);
					}
					this._list_BMPCode.Entity = value;
					if ((value != null))
					{
						value.bmp_ags.Add(this);
						this._fk_BMPCode_code = value.pk_BMPCode_code;
					}
					else
					{
						this._fk_BMPCode_code = default(string);
					}
					this.SendPropertyChanged("list_BMPCode");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bmp_ags(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag3 = this;
		}
		
		private void detach_bmp_ags(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag3 = null;
		}
		
		private void attach_bmp_ags1(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag4 = this;
		}
		
		private void detach_bmp_ags1(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag4 = null;
		}
		
		private void attach_bmp_ags2(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag5 = this;
		}
		
		private void detach_bmp_ags2(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag5 = null;
		}
		
		private void attach_bmp_ags3(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag6 = this;
		}
		
		private void detach_bmp_ags3(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.bmp_ag6 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.list_BMPCode")]
	public partial class list_BMPCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _pk_BMPCode_code;
		
		private string _code;
		
		private System.Nullable<int> _priority;
		
		private EntitySet<bmp_ag> _bmp_ags;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpk_BMPCode_codeChanging(string value);
    partial void Onpk_BMPCode_codeChanged();
    partial void OncodeChanging(string value);
    partial void OncodeChanged();
    partial void OnpriorityChanging(System.Nullable<int> value);
    partial void OnpriorityChanged();
    #endregion
		
		public list_BMPCode()
		{
			this._bmp_ags = new EntitySet<bmp_ag>(new Action<bmp_ag>(this.attach_bmp_ags), new Action<bmp_ag>(this.detach_bmp_ags));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pk_BMPCode_code", DbType="NVarChar(8) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string pk_BMPCode_code
		{
			get
			{
				return this._pk_BMPCode_code;
			}
			set
			{
				if ((this._pk_BMPCode_code != value))
				{
					this.Onpk_BMPCode_codeChanging(value);
					this.SendPropertyChanging();
					this._pk_BMPCode_code = value;
					this.SendPropertyChanged("pk_BMPCode_code");
					this.Onpk_BMPCode_codeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="NVarChar(24) NOT NULL", CanBeNull=false)]
		public string code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this.OncodeChanging(value);
					this.SendPropertyChanging();
					this._code = value;
					this.SendPropertyChanged("code");
					this.OncodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_priority", DbType="Int")]
		public System.Nullable<int> priority
		{
			get
			{
				return this._priority;
			}
			set
			{
				if ((this._priority != value))
				{
					this.OnpriorityChanging(value);
					this.SendPropertyChanging();
					this._priority = value;
					this.SendPropertyChanged("priority");
					this.OnpriorityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="list_BMPCode_bmp_ag", Storage="_bmp_ags", ThisKey="pk_BMPCode_code", OtherKey="fk_BMPCode_code")]
		public EntitySet<bmp_ag> bmp_ags
		{
			get
			{
				return this._bmp_ags;
			}
			set
			{
				this._bmp_ags.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_bmp_ags(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.list_BMPCode = this;
		}
		
		private void detach_bmp_ags(bmp_ag entity)
		{
			this.SendPropertyChanging();
			entity.list_BMPCode = null;
		}
	}
	
	public partial class FarmNMCPAwardHistoryResult
	{
		
		private string _farmID;
		
		private System.Nullable<decimal> _startingYear;
		
		private System.Nullable<decimal> _nmcpBalYr1;
		
		private System.Nullable<decimal> _nmcpBalYr2;
		
		private System.Nullable<decimal> _nmcpBalYr3;
		
		private System.Nullable<decimal> _nmcpBalYr4;
		
		private System.Nullable<decimal> _nmcpBalYr5;
		
		private System.Nullable<decimal> _nmcpBalYr6;
		
		private System.Nullable<decimal> _nmcpBalYr7;
		
		private System.Nullable<decimal> _nmcpBalYr8;
		
		private System.Nullable<decimal> _award_total;
		
		private System.Nullable<int> _fk_farmBusiness;
		
		public FarmNMCPAwardHistoryResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_farmID", DbType="NVarChar(16)")]
		public string farmID
		{
			get
			{
				return this._farmID;
			}
			set
			{
				if ((this._farmID != value))
				{
					this._farmID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_startingYear", DbType="Decimal(18,0)")]
		public System.Nullable<decimal> startingYear
		{
			get
			{
				return this._startingYear;
			}
			set
			{
				if ((this._startingYear != value))
				{
					this._startingYear = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr1", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr1
		{
			get
			{
				return this._nmcpBalYr1;
			}
			set
			{
				if ((this._nmcpBalYr1 != value))
				{
					this._nmcpBalYr1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr2", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr2
		{
			get
			{
				return this._nmcpBalYr2;
			}
			set
			{
				if ((this._nmcpBalYr2 != value))
				{
					this._nmcpBalYr2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr3", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr3
		{
			get
			{
				return this._nmcpBalYr3;
			}
			set
			{
				if ((this._nmcpBalYr3 != value))
				{
					this._nmcpBalYr3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr4", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr4
		{
			get
			{
				return this._nmcpBalYr4;
			}
			set
			{
				if ((this._nmcpBalYr4 != value))
				{
					this._nmcpBalYr4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr5", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr5
		{
			get
			{
				return this._nmcpBalYr5;
			}
			set
			{
				if ((this._nmcpBalYr5 != value))
				{
					this._nmcpBalYr5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr6", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr6
		{
			get
			{
				return this._nmcpBalYr6;
			}
			set
			{
				if ((this._nmcpBalYr6 != value))
				{
					this._nmcpBalYr6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr7", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr7
		{
			get
			{
				return this._nmcpBalYr7;
			}
			set
			{
				if ((this._nmcpBalYr7 != value))
				{
					this._nmcpBalYr7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nmcpBalYr8", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> nmcpBalYr8
		{
			get
			{
				return this._nmcpBalYr8;
			}
			set
			{
				if ((this._nmcpBalYr8 != value))
				{
					this._nmcpBalYr8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_award_total", DbType="Decimal(8,2)")]
		public System.Nullable<decimal> award_total
		{
			get
			{
				return this._award_total;
			}
			set
			{
				if ((this._award_total != value))
				{
					this._award_total = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fk_farmBusiness", DbType="Int")]
		public System.Nullable<int> fk_farmBusiness
		{
			get
			{
				return this._fk_farmBusiness;
			}
			set
			{
				if ((this._fk_farmBusiness != value))
				{
					this._fk_farmBusiness = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
